name: Bug Report
description: Report a bug with GitHub Agent
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        **Problem**: Describe the issue you encountered
        **Minimal Reproduction**: Steps to reproduce the behavior
      placeholder: |
        **Problem**: GitHub Agent fails to create issues when...
        **Minimal Reproduction**:
        1. Initialize agent with...
        2. Run command...
        3. Error occurs...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: The agent should successfully create an issue...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages or logs.
      placeholder: |
        Error: Failed to create issue
        Stack trace: ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of GitHub Agent are you using?
      placeholder: "1.0.2 or main branch"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your setup details (Node.js version, OS, etc.)
      placeholder: |
        - Node.js: v18.17.0
        - OS: macOS 13.4
        - Docker: 24.0.2
      render: markdown
    validations:
      required: false
