blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/agent-contrib/github-agent/discussions
    about: Ask questions and discuss GitHub Agent usage
  - name: Security Issues
    url: https://github.com/agent-contrib/github-agent/security/advisories/new
    about: Report security vulnerabilities privately
