name: Feature Request
description: Suggest a new feature for GitHub Agent
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        **Problem**: What problem does this feature solve?
        **Proposed Solution**: How should this feature work?
      placeholder: |
        **Problem**: Currently, GitHub Agent cannot...
        **Proposed Solution**: Add a new command that allows users to...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: How should this feature work? Include usage examples.
      placeholder: |
        ```typescript
        const agent = new GithubAgent(...);
        await agent.run("new command that does...");
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds you've considered?
      placeholder: I could manually do X, but it would be better if...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or related issues?
    validations:
      required: false
